name: Deploy Bicep file
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@main

    - name: Configure Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install npm dependencies
      run: npm ci

    - name: Build react app
      run: npm run build


    - name: Log into Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy Bicep file
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        template: ./.github/workflows/main.bicep
        parameters: swaName=${{ secrets.SWA_NAME }} buildLocation=./dist
        failOnStdErr: false